//! Reproduce the checked-in README previews from the current synthetic configuration.

use std::{fmt::Write, path::Path};

use anyhow::{Context, Result, ensure};
use clap::Parser;
use sourcefield_core::{Config, Snapshot, build_state};
use sourcefield_render::{PreparedPresentation, Theme};

/// Refresh is explicit; the default command only verifies existing documentation assets.
#[derive(Parser)]
struct Arguments {
    /// Replace all three documentation SVGs after reviewing a renderer or fixture change.
    #[arg(long)]
    write: bool,
}

/// Fixed input time keeps the preview independent of the clock and local environment.
const FIXTURE_TIME: &str = "1970-01-01T00:00:00Z";

/// Render the same approved fixture once and reuse its presentation across all output variants.
fn previews() -> Result<[(String, String); 3]> {
    let config: Config = toml::from_str(include_str!("../../../config/profile.toml"))?;
    let snapshot: Snapshot =
        serde_json::from_str(include_str!("../../../config/offline-snapshot.json"))?;

    let state = build_state(&config, &snapshot, FIXTURE_TIME)?;
    let presentation = PreparedPresentation::new(&state);
    let variants = [
        ("sourcefield.dark.svg", Theme::Dark, true),
        ("sourcefield.light.svg", Theme::Light, true),
        ("sourcefield.static.svg", Theme::Dark, false),
    ];

    Ok(variants.map(|(name, theme, motion)| {
        let svg = presentation.render(theme, motion);

        (name.to_owned(), ascii_xml(&svg))
    }))
}

/// Keep repository assets ASCII without altering Unicode text shown by the SVG renderer.
fn ascii_xml(source: &str) -> String {
    let mut output = String::with_capacity(source.len());
    for character in source.chars() {
        if character.is_ascii() {
            output.push(character);
        } else {
            write!(&mut output, "&#{};", u32::from(character))
                .expect("writing to an in-memory String cannot fail");
        }
    }

    output
}

/// Compare the complete document so layout, copy and animation changes cannot pass silently.
fn verify_preview(name: &str, expected: &str, actual: &str) -> Result<()> {
    ensure!(
        actual == expected,
        "documentation preview {name} is stale; run cargo run --locked -p sourcefield-cli \
         --example documentation_previews -- --write and review the three SVG diffs"
    );

    Ok(())
}

/// Resolve the source checkout independently of the caller's working directory.
fn preview_directory() -> &'static Path {
    Path::new(concat!(env!("CARGO_MANIFEST_DIR"), "/../../docs/preview"))
}

/// Update only intentional documentation assets, or fail if any generated bytes have drifted.
fn main() -> Result<()> {
    let arguments = Arguments::parse();
    let rendered = previews()?;
    for (name, svg) in rendered {
        let path = preview_directory().join(&name);
        if arguments.write {
            std::fs::write(&path, svg).with_context(|| format!("write preview {name}"))?;
        } else {
            let actual = std::fs::read_to_string(&path)
                .with_context(|| format!("read documentation preview {name}"))?;

            verify_preview(&name, &svg, &actual)?;
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn checked_in_previews_match_the_current_renderer() {
        let expected = previews().unwrap();
        let actual = expected
            .each_ref()
            .map(|(name, _)| std::fs::read_to_string(preview_directory().join(name)).unwrap());

        let results = expected
            .iter()
            .zip(&actual)
            .map(|((name, svg), stored)| verify_preview(name, svg, stored))
            .collect::<Vec<_>>();

        assert!(results.iter().all(Result::is_ok));
    }

    #[test]
    fn stale_preview_is_rejected() {
        let [(name, expected), _, _] = previews().unwrap();
        let stale = expected.replacen("<svg ", "<svg data-stale=\"true\" ", 1);

        let result = verify_preview(&name, &expected, &stale);

        assert!(result.unwrap_err().to_string().contains("is stale"));
    }

    #[test]
    fn unicode_text_is_preserved_as_xml_character_references() {
        let source = "<text>A \u{b7} B &amp; \u{1f680}</text>";

        let encoded = ascii_xml(source);

        assert_eq!(encoded, "<text>A &#183; B &amp; &#128640;</text>");
        assert!(encoded.is_ascii());
    }
}
